### PR TITLE
provide alternative API URL for EU region in curl example

### PR DESCRIPTION
**Pull request by adrienjoly**

### CODE REVIEW

**Comment by thrawn01** [comment]
Not sure this is the correct place for mentioning the EU endpoint. I feel like there should be a section on the documentation where we discuss the EU region and how it differs and how to access it. @highlycaffeinated thoughts?

**Comment by thrawn01** [comment]
See #362

**Comment by highlycaffeinated** [comment]
I agree. I'd prefer to use something like API_BASE_URL and update `api-intro.rst` to talk about the regional difference in endpoints.

**Comment by thrawn01** [comment]
I'll make a PR today that updates the api-intro doc and mentions the EU endpoint.

**Pull request closed without merging**
