### PR TITLE
Updated PHP docs for version 2.0 of the mailgun client

### PR DESCRIPTION
**Pull request by Nyholm**
Related to https://github.com/mailgun/mailgun-php/pull/94

### CODE REVIEW

**Comment by ethanclevenger91** [comment]
Might be helpful to also include an example of how to pass Guzzle arguments to this? Maybe that falls to the PHP-HTTP docs, but it had me for a while before I got to something like:

```
$mailgun = new Mailgun('api-key', new \Http\Adapter\Guzzle6\Client(new \GuzzleHttp\Client(['debug' => true])));
```

**Comment by Nyholm** [comment]
Yes agreed. But that should be in the mailgun client webpage, right? I believe Mailgun just want the minimal documentation to get started here.

**Comment by Nyholm** [comment]
Ping

**Comment by pirogoeth** [comment]
@Nyholm I'll go ahead and merge this but we definitely need to make sure to update the docs again once we push out the new PHP SDK release.

**Comment by Nyholm** [comment]
Agreed. 
But it is a bit lower priority on this. These docs are okey for 2.x. I hope we do not **have to** update the docs in a great while (when the client tags 3.0) but we **should** focus on the docs after 2.2 or 2.3 is released.

**Comment by pirogoeth** [comment]
@Nyholm :+1:

**Pull request merged**
